### PR TITLE
feat: Qdrant vectorstore

### LINKED ISSUE #125: feat(core): Qdrant integration
Currently, we only support local and ChromaDB vector stores. We would like to add support for Qdrant:

- It is very feature-rich and performant; for example, it supports hybrid search, which ChromaDB lacks.
- It has a slightly different API than ChromaDB, allowing us to test if our VectorStore abstraction is robust enough to cover different vector stores.

### PR DESCRIPTION
**Pull request by Anush008**
## Description

This PR adds support for Qdrant - https://qdrant.tech/ to be used as a vectorstore in Ragbits.

Resolves #125 

I've QA tested the examples and unit tests have been added.

### CODE REVIEW

**Comment by mhordynski** [comment]
Hello @Anush008 , thank you for your contribution!
@micpst will perform testing and code review on our side

**Comment by micpst** [comment]
Hi @Anush008, thank you for your PR. I'll review it after we release 0.3. Currently, the Qdrant integration is scheduled for the 0.4 release and is a lower priority at the moment.

**Comment by Anush008** [comment]
Thanks @micpst.

**Comment by Anush008** [comment]
🙏

**Comment by micpst** [comment]
Adjusted the code to the changes from main and tested, confirms this PR works correct. Brilliant, thanks @Anush008!

**Pull request merged**
